FROM php:5.6-fpm

RUN apt-get update && apt-get install mcedit php5-dev php5-cli php-pear -y && /usr/local/bin/docker-php-ext-install mysqli pdo pdo_mysql && pecl install apcu-4.0.11 xdebug

CMD ["php-fpm"]